# Generated by Django 2.2.7 on 2019-12-13 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
                ('theme', models.TextField()),
                ('discription', models.TextField()),
                ('spectators', models.TextField()),
                ('longliness', models.DurationField(verbose_name='longliness в формате DD HH:MM:SS')),
            ],
        ),
    ]
