# Generated by Django 2.2.7 on 2019-12-09 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('theme', models.TextField()),
                ('discription', models.TextField()),
                ('spectators', models.TextField()),
                ('longliness', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
