# Generated by Django 2.2.7 on 2019-12-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191213_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clas',
            field=models.IntegerField(default=0, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Ваша почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='Имя'),
        ),
    ]
