# Generated by Django 2.2.7 on 2019-12-15 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191213_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания (редактированию не подлежит)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проведения лекции-консультации       '),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='discription',
            field=models.TextField(verbose_name='Подробное раскрытие темы                  '),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Ваша почта                                '),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='longliness',
            field=models.DurationField(verbose_name='Продолжительность в формате HH:MM:SS      '),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='spectators',
            field=models.TextField(verbose_name='Целевая аудитория                         '),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='theme',
            field=models.TextField(verbose_name='Общая тема лекции-консультации             '),
        ),
    ]
