# Generated by Django 2.2.7 on 2019-12-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191215_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.TextField(default='', verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
