# Generated by Django 2.2.7 on 2019-12-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191219_0028'),
        ('blog', '0005_auto_20191209_1522'),
    ]

    operations = [
    ]
